# Generated by Django 2.1.2 on 2018-11-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becario',
            name='curso',
            field=models.ManyToManyField(to='blog.Curso'),
        ),
    ]
