# Generated by Django 2.1.2 on 2018-11-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_opinion_becario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='becario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Becario'),
        ),
    ]
