# Generated by Django 2.1.2 on 2018-11-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181107_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='curso',
            field=models.ManyToManyField(to='blog.Curso'),
        ),
    ]
